### ISSUE TITLE
Browser is not caching resources

### ISSUE THREAD

**Issue by Flerex** [schme16/gitcdn.xyz#28]
I just noticed that requests to a `gitcdn.xyz` URL returns a 301 status code to the URL to the last revision of the resource, as expected. Nevertheless, the URL of the revision always returns a 200 status code with a Expires header to the current time. This means that the resource will never be cached.

![screen shot 2018-03-24 at 11 20 37](https://user-images.githubusercontent.com/3910120/37862959-376d1310-2f56-11e8-86ba-857b1469d9e6.png)

**Comment by schme16** [comment]
I've not found any issues when loading the resource _as_ a resource
i.e. a script tag: `<script src="https://gitcdn.xyz/cdn/agamemnus/history-easy.js/db15970e6caa96ac3b6836ad8782192cd6c0fc10/history-easy-1.0.js"></script src=""></script>` loaded from a html document seems to be cacheing correctly- my suspicion is this is the culprit:
![image](https://user-images.githubusercontent.com/116081/37941270-cb95523a-31b0-11e8-8132-fe2726f2a755.png)


That is, the browser asks the server to explicitly _NOT_ cache many mime types when viewing them directly.

Hope that explains it a little better!

**Comment by Flerex** [comment]
I don't understand why then this jQuery file is cached if that very same header is being sent with the request:

![screen shot 2018-03-27 at 13 35 26](https://user-images.githubusercontent.com/3910120/37964995-c9be052a-31c3-11e8-9340-b5dda3781326.png)

The script is being used as a resource, but with the URL that points to the last commit (I don't know if it has something to do with it).

**Comment by schme16** [comment]
Can I ask how you include the file, as in, is it by using a regular script tag such as `<script src="https://gitcdn.xyz/repo/Flerex/cdn/master/fm/custom-profile.js"></script>` or is is by using javascript (vanilla xhr, jquery, etc), as that may be causing some issues here.

As you can see from the below, the file `https://gitcdn.xyz/repo/Flerex/cdn/master/fm/custom-profile.js` caches just fine when using the script tag to include it (I've actually got it added several times, on the page, but Chrome only shows one request due to it grabbing the cache on subsequent lookups)
![image](https://user-images.githubusercontent.com/116081/38007121-320a69b2-328b-11e8-88d3-a84dee1290ad.png)

**Comment by Flerex** [comment]
Well it's not my web but I guess that there's no problem on sharing it as it's a testing forum:

http://in-noctem.foroactivo.com

That is the web where the screenshots come frome. As you can see in the DOM, the resource is loaded in a script tag just like this:

    <script src="https://gitcdn.xyz/repo/Flerex/cdn/master/fm/custom-profile.js" type="text/javascript"></script>

**Comment by schme16** [comment]
That is _REALLY_ strange... I've not heard of Firefox having a different cache scheme to Webkit/Blink but I'll look into it!
