### ISSUE TITLE
gitcdn.xyz down

### ISSUE THREAD

**Issue by atsger** [schme16/gitcdn.xyz#4]
At the time of writing this your service seems to be down. :cry:
Hope you can fix the issue soon...

*Hint: maybe it's a DNS issue according to this: http://viewdns.info/ismysitedown/?domain=gitcdn.xyz*

**Comment by schme16** [comment]
Thanks for the heads up!


I'm still trying to track this issue down: it seems to be some issue with either my Registrar (Hover) or my CDN (Cloudflare), as the server is up and responding to requests as per usual; I cannot see what the issue is at this time, however, as the domain is paid for another few years, though I suspect it's that Hover is not listing the nameservers correctly- Both have been contacted and I'll be posting here as updates become available!

**Comment by schme16** [comment]
8:28am AEST
Have spoken with a rep. from Hover- They seem to think the issue is with Cloudflare; have just submitted a support ticket

**Comment by schme16** [comment]
2:40pm AEST
Still no word from Cloudflare; but I've migrated the server from a private VPS to Heroku, and updates all of the DNS details. Temporary URI: https://gitcdn.herokuapp.com/

**Comment by schme16** [comment]
7:48am AEST - Day 2
Finally received a network analysis from Cloudflare; looks like the issue is DEFINITELY with Hover

**Comment by schme16** [comment]
8:44am - Day 2
After a lengthy discussion with a Hover tech (who still insisted nothing was wrong) he did a dns prob, confirmed the issue (AT LAST!) then informed me that the reason it was taken down was that they had sent me a correspondence alerting me the site was marked for Phishing (which is ridiculous; you don't blame jQuery if someone uses their library for bad things), correspondence I can guarantee  I never received- The issue is with their compliance department now, so I'm hoping to work with them to sort it out in the next few hours

**Comment by schme16** [comment]
Finally have this all sorted out; Turns out the .xyz registry had received a phishing complaint from this url (someone has been naughty!) but rather than contact me and let me know what repo was wrong, so that I could blacklist it, they decided to whole hog remove the domain from me...

I've explained the site to them, and they've given it back, but I'm moving away from this domain as soon as I can; clearly the .xyz registrar council has no idea of web technologies

New domain: https://gitcdn.link
