### ISSUE TITLE
gitcdn.xyz and gitcdn.link seem to be down

### ISSUE THREAD

**Issue by pentacular** [schme16/gitcdn.xyz#60]
Just FYI

**Comment by p1r473** [comment]
Yup, getting 500 internal server error when accessing link via the CDN

**Comment by Jeff-Tian** [comment]
Yeah, can reproduce with https://gitcdn.xyz/repo/Jeff-Tian/uni-sso/master/entities.tex, but others looks good.

**Comment by schme16** [comment]
Some background: Due to some of the innefficiencies I had when using the github api, occasionally the service would hit the rate-limits, causing new/uncached repos to fail.
I've re-written the entire handler function to fix this. Stability has therefore incread significantly!

@Jeff-Tian The linked repo seems to be gone now, but just for example: https://gitcdn.xyz/repo/Jeff-Tian/uni-alarm/master/README.md is working just the way it should now :)
