### ISSUE TITLE
support for private repos?

### ISSUE THREAD

**Issue by matthewselby** [schme16/gitcdn.xyz#7]
Does gitcdn.xyz currently support private repos? Couldn't find any mention of private repos in the documentation. So far no luck with private raw links with access tokens.

**Comment by schme16** [comment]
Not just yet, I've got to figure a way to let the repo owner give
permission for certain items to be public (otherwise the site could be used
as a way to get into all of a private repo) or for domain locking  (I'm
leaning towards adding a GitHub sign in and letting the user select the
exact files that they want opened up)

**Comment by matthewselby** [comment]
That makes sense. Thanks for your prompt reply!
